### ISSUE TITLE
打开显示 Class 'kartik\widgets\ActiveForm' not found

### ISSUE THREAD

**Issue by spc324** [BigKuCha/yga#5]
请问这是怎么回事呢  打开显示 Class 'kartik\widgets\ActiveForm' not found

**Comment by BigKuCha** [comment]
缺少组件啊，vendor不要从其他地方拷贝过来。需要的扩展在composer.json里都定义好了，需要都安装上

**Comment by spc324** [comment]
刚开始学习YII  这个框架安装好麻烦的啊 谢谢了 我再研究研究
